#spring:
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:postgresql://localhost:5432/library
#    username: postgres
#    password: postgres
#
#hibernate:
#  hbm2ddl:
#    auto: update